// src/constants.js
export const countriesCurrencies = [
    { country: "United States", currency: "USD - United States Dollar" },
    { country: "Eurozone", currency: "EUR - Euro" },
    { country: "United Kingdom", currency: "GBP - British Pound Sterling" },
    { country: "Japan", currency: "JPY - Japanese Yen" },
    { country: "Canada", currency: "CAD - Canadian Dollar" },
    { country: "Australia", currency: "AUD - Australian Dollar" },
    { country: "Switzerland", currency: "CHF - Swiss Franc" },
    { country: "China", currency: "CNY - Chinese Yuan" },
    { country: "India", currency: "INR - Indian Rupee" },
    { country: "Brazil", currency: "BRL - Brazilian Real" },
    { country: "South Africa", currency: "ZAR - South African Rand" },
    { country: "Russia", currency: "RUB - Russian Ruble" },
    { country: "Mexico", currency: "MXN - Mexican Peso" },
    { country: "Singapore", currency: "SGD - Singapore Dollar" },
    { country: "New Zealand", currency: "NZD - New Zealand Dollar" },
    { country: "Turkey", currency: "TRY - Turkish Lira" },
    { country: "South Korea", currency: "KRW - South Korean Won" },
    { country: "Saudi Arabia", currency: "SAR - Saudi Riyal" },
    { country: "Nigeria", currency: "NGN - Nigerian Naira" },
    { country: "Argentina", currency: "ARS - Argentine Peso" },
    { country: "Norway", currency: "NOK - Norwegian Krone" },
    { country: "Sweden", currency: "SEK - Swedish Krona" },
    { country: "Denmark", currency: "DKK - Danish Krone" },
    { country: "Poland", currency: "PLN - Polish Zloty" },
    { country: "Israel", currency: "ILS - Israeli Shekel" },
    { country: "Thailand", currency: "THB - Thai Baht" },
    { country: "Malaysia", currency: "MYR - Malaysian Ringgit" },
    { country: "Philippines", currency: "PHP - Philippine Peso" },
    { country: "Indonesia", currency: "IDR - Indonesian Rupiah" },
    { country: "Pakistan", currency: "PKR - Pakistani Rupee" },
    { country: "Vietnam", currency: "VND - Vietnamese Dong" },
    { country: "Egypt", currency: "EGP - Egyptian Pound" },
    { country: "Kenya", currency: "KES - Kenyan Shilling" },
    { country: "Chile", currency: "CLP - Chilean Peso" },
    { country: "Colombia", currency: "COP - Colombian Peso" },
    { country: "United Arab Emirates", currency: "AED - UAE Dirham" },
    { country: "Qatar", currency: "QAR - Qatari Riyal" },
    { country: "Oman", currency: "OMR - Omani Rial" },
    { country: "Kuwait", currency: "KWD - Kuwaiti Dinar" },
    // Add more countries and currencies as needed
];
